# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(495, 406)
        MainWindow.setMinimumSize(QtCore.QSize(495, 406))
        MainWindow.setMaximumSize(QtCore.QSize(495, 406))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Clock = QtWidgets.QLabel(self.centralwidget)
        self.Clock.setGeometry(QtCore.QRect(270, 30, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Clock.setFont(font)
        self.Clock.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Clock.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Clock.setLineWidth(2)
        self.Clock.setText("")
        self.Clock.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Clock.setObjectName("Clock")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 290, 481, 91))
        self.stackedWidget.setAutoFillBackground(True)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_11 = QtWidgets.QLabel(self.page)
        self.label_11.setGeometry(QtCore.QRect(10, 0, 71, 71))
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_11.setLineWidth(0)
        self.label_11.setMidLineWidth(0)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("icons/home.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.cam_lb = QtWidgets.QLabel(self.page)
        self.cam_lb.setGeometry(QtCore.QRect(380, 0, 71, 71))
        self.cam_lb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cam_lb.setText("")
        self.cam_lb.setPixmap(QtGui.QPixmap("icons/cam.png"))
        self.cam_lb.setScaledContents(True)
        self.cam_lb.setObjectName("cam_lb")
        self.home_btn = QtWidgets.QPushButton(self.page)
        self.home_btn.setGeometry(QtCore.QRect(10, 0, 71, 71))
        self.home_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.home_btn.setText("")
        self.home_btn.setCheckable(False)
        self.home_btn.setAutoDefault(False)
        self.home_btn.setDefault(False)
        self.home_btn.setFlat(True)
        self.home_btn.setObjectName("home_btn")
        self.rb_home = QtWidgets.QRadioButton(self.page)
        self.rb_home.setEnabled(False)
        self.rb_home.setGeometry(QtCore.QRect(40, 70, 16, 20))
        self.rb_home.setText("")
        self.rb_home.setChecked(True)
        self.rb_home.setAutoExclusive(False)
        self.rb_home.setObjectName("rb_home")
        self.rb_cam = QtWidgets.QRadioButton(self.page)
        self.rb_cam.setEnabled(False)
        self.rb_cam.setGeometry(QtCore.QRect(410, 70, 16, 20))
        self.rb_cam.setText("")
        self.rb_cam.setChecked(True)
        self.rb_cam.setObjectName("rb_cam")
        self.cam_btn = QtWidgets.QPushButton(self.page)
        self.cam_btn.setGeometry(QtCore.QRect(380, 0, 71, 71))
        self.cam_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cam_btn.setText("")
        self.cam_btn.setAutoDefault(False)
        self.cam_btn.setDefault(False)
        self.cam_btn.setFlat(True)
        self.cam_btn.setObjectName("cam_btn")
        self.tmp_lb_3 = QtWidgets.QLabel(self.page)
        self.tmp_lb_3.setGeometry(QtCore.QRect(140, 0, 71, 81))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(22)
        self.tmp_lb_3.setFont(font)
        self.tmp_lb_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tmp_lb_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tmp_lb_3.setLineWidth(0)
        self.tmp_lb_3.setText("")
        self.tmp_lb_3.setPixmap(QtGui.QPixmap("icons/icons8-ruler-96.png"))
        self.tmp_lb_3.setScaledContents(True)
        self.tmp_lb_3.setAlignment(QtCore.Qt.AlignCenter)
        self.tmp_lb_3.setObjectName("tmp_lb_3")
        self.tmp_lb_4 = QtWidgets.QLabel(self.page)
        self.tmp_lb_4.setGeometry(QtCore.QRect(260, -10, 81, 101))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(22)
        self.tmp_lb_4.setFont(font)
        self.tmp_lb_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tmp_lb_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tmp_lb_4.setLineWidth(0)
        self.tmp_lb_4.setText("")
        self.tmp_lb_4.setPixmap(QtGui.QPixmap("icons/light sens.png"))
        self.tmp_lb_4.setScaledContents(False)
        self.tmp_lb_4.setAlignment(QtCore.Qt.AlignCenter)
        self.tmp_lb_4.setObjectName("tmp_lb_4")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.tmp_lb_2 = QtWidgets.QLabel(self.centralwidget)
        self.tmp_lb_2.setGeometry(QtCore.QRect(20, 10, 101, 121))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(22)
        self.tmp_lb_2.setFont(font)
        self.tmp_lb_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tmp_lb_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tmp_lb_2.setLineWidth(0)
        self.tmp_lb_2.setText("")
        self.tmp_lb_2.setPixmap(QtGui.QPixmap("icons/therm.png"))
        self.tmp_lb_2.setAlignment(QtCore.Qt.AlignCenter)
        self.tmp_lb_2.setObjectName("tmp_lb_2")
        self.tmp_lb = QtWidgets.QLabel(self.centralwidget)
        self.tmp_lb.setGeometry(QtCore.QRect(110, 30, 81, 71))
        self.tmp_lb.setMinimumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.tmp_lb.setFont(font)
        self.tmp_lb.setStyleSheet("border-radius: 8px; ")
        self.tmp_lb.setFrameShape(QtWidgets.QFrame.Panel)
        self.tmp_lb.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tmp_lb.setLineWidth(1)
        self.tmp_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.tmp_lb.setObjectName("tmp_lb")
        self.dial_lb = QtWidgets.QLabel(self.centralwidget)
        self.dial_lb.setGeometry(QtCore.QRect(20, 190, 111, 41))
        self.dial_lb.setMinimumSize(QtCore.QSize(41, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.dial_lb.setFont(font)
        self.dial_lb.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.dial_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.dial_lb.setObjectName("dial_lb")
        self.date = QtWidgets.QLabel(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(330, 90, 111, 20))
        self.date.setMinimumSize(QtCore.QSize(111, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.date.setFont(font)
        self.date.setText("")
        self.date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.date.setObjectName("date")
        self.cam = QtWidgets.QLabel(self.centralwidget)
        self.cam.setGeometry(QtCore.QRect(330, 160, 121, 101))
        self.cam.setAutoFillBackground(True)
        self.cam.setFrameShape(QtWidgets.QFrame.Box)
        self.cam.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cam.setText("")
        self.cam.setObjectName("cam")
        self.alert = QtWidgets.QLabel(self.centralwidget)
        self.alert.setGeometry(QtCore.QRect(460, 150, 21, 20))
        self.alert.setFrameShape(QtWidgets.QFrame.Panel)
        self.alert.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alert.setText("")
        self.alert.setObjectName("alert")
        self.dial_lb_2 = QtWidgets.QLabel(self.centralwidget)
        self.dial_lb_2.setGeometry(QtCore.QRect(170, 190, 111, 41))
        self.dial_lb_2.setMinimumSize(QtCore.QSize(41, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.dial_lb_2.setFont(font)
        self.dial_lb_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.dial_lb_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dial_lb_2.setObjectName("dial_lb_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 240, 81, 16))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 240, 31, 16))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Hub"))
        self.tmp_lb.setText(_translate("MainWindow", "--"))
        self.dial_lb.setText(_translate("MainWindow", "0"))
        self.dial_lb_2.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Distancia"))
        self.label_2.setText(_translate("MainWindow", "Luz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
